import type {Metadata} from "next";
import {Geist, Geist_Mono, Afacad} from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const afacad = Afacad({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${afacad.className} antialiased`}
        >
        <Navigation/>
        {children}
        </body>
        </html>
    );
}
