import type {Metadata} from "next";
import localFont from "next/font/local";
import {Afacad} from 'next/font/google';
import "./globals.css";
import AppLayout from "@/layouts/app-layout";
import CartProvider from "@/lib/store/cart";
import {fetchCart} from "@/lib/services/cart-service";
import {WishlistProvider} from "@/lib/store/wishlist";
import {fetchWishlist} from "@/lib/services/wishlist-service";
import {getSession} from "@/lib/session";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const saira = Afacad({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    const cookie = await getSession();

    const cartInitialState = {
        products: [],
        quantity: 0,
        totalPrice: 0,
    }

    const wishlistInitialState = [];

    if (cookie && typeof cookie?.user !== 'undefined') {
        const [cart, wishlist] = await Promise.all([
            fetchCart(cookie.user.cartId),
            fetchWishlist(cookie.user.token),
        ]);

        cartInitialState.quantity = cart.totalQuantity;
        cartInitialState.totalPrice = cart.cost.totalAmount.amount;
        cartInitialState.products = cart.lines.nodes;

        wishlistInitialState.push(...wishlist);
    }

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} ${saira.className}`}>
        <CartProvider cartInitialState={cartInitialState}>
            <WishlistProvider initialState={wishlistInitialState}>
                <AppLayout>
                    {children}
                </AppLayout>
            </WishlistProvider>
        </CartProvider>
        </body>
        </html>
    );
}
