import type {Metadata} from "next";
import {Geist, Geist_Mono, Afacad} from "next/font/google";
import Navigation from "@/components/navigation/navigation";
import "./globals.css";
import CartProvider from "@/lib/context/cart";
import Cart from "@/components/cart";
import {getCartId, getSession} from "@/lib/session";
import {fetchCart} from "@/lib/api/cart.api";
import WishlistProvider from "@/lib/context/wishlist";
import {Toaster} from "@/components/ui/toaster";
import {fetchWishlist} from "@/lib/api/wishlist.api";
import {getWishlistId} from "@/lib/actions/wishlist.actions";
import {fetchAvailableShippingCountries} from "@/lib/api/order.api";
import ShopProvider from "@/lib/context/shop";
import {getCountryIso} from "@/lib/utils/server/customer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const afacad = Afacad({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    const [cartId, wishlistId, countryISO, session] = await Promise.all([
        getCartId(),
        getWishlistId(),
        getCountryIso(),
        getSession(),
    ])

    const cartPromise = fetchCart(cartId);
    const wishlistPromise = fetchWishlist(wishlistId);
    const availableShippingCountriesPromise = fetchAvailableShippingCountries();

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${afacad.className} antialiased bg-stone-100`}
        >
        <Toaster/>
        <ShopProvider
            countryISO={countryISO}
            availableShippingCountriesPromise={availableShippingCountriesPromise}
        >
            <CartProvider cartPromise={cartPromise}>
                <WishlistProvider wishlistPromise={wishlistPromise}>
                    <Navigation/>
                    <Cart session={session}/>
                    {children}
                </WishlistProvider>
            </CartProvider>
        </ShopProvider>
        </body>
        </html>
    );
}
